//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffeeX.Model
{
    using coffeeX.ViewModel;
    using System;
    using System.Collections.Generic;

    public partial class PaymentDetail : BaseViewModel
    {
        public int paymentID { get; set; }
        public int ingredientID { get; set; }
        public int ingredientQuantity
        {
            get => _ingredientQuantity
            ; set
            {
                _ingredientQuantity = value;
                OnPropertyChanged();

            }
        }
        private int _ingredientQuantity;

        public virtual Ingredient Ingredient
        {
            get => _Ingredient; set
            {
                _Ingredient = value;
                OnPropertyChanged();
            }
        }
        private Ingredient _Ingredient;
        public virtual PaymentVoucher PaymentVoucher { get; set; }
    }
}
