//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffeeX.Model
{
    using coffeeX.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail : BaseViewModel
    {
        public int receiptID { get; set; }
        public int beverageID { get; set; }
        private int _quantity;
        public int quantity { get => _quantity; set
            {
                _quantity = value;
                if(Beverage!=null)
                total = _quantity * Beverage.beveragePrice;
                OnPropertyChanged();
            } }
        private double _total;
        public double total { get => _total; set
            {
                _total = value;
                OnPropertyChanged();
            } }
    
        public virtual Beverage Beverage { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
