//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace coffeeX.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public int receiptID { get; set; }
        public int beverageID { get; set; }
        public int quantity { get; set; }
    
        public virtual Beverage Beverage { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
